enum KEYS {UP, DOWN, LEFT, RIGHT, SPACE, X, C};
enum STATES {MAINMENU, WALKING, FIGHTING, PAUSING};
enum WALK {WALK_DOWN,  WALK_LEFT, WALK_RIGHT, WALK_UP};
enum HERO_CLASS {HERO_LINK, HERO_IKE, HERO_MARTH, HERO_IKAROS, HERO_ZELDA, HERO_ZSSAMUS, HERO_PEACH, HERO_PALUTENA};
enum DRAGON_ACTION {DRAGON_STAND, DRAGON_BREATH};
enum BATTLE_STATES {HERO_SELECT, HERO_ATTACK, OPPONENT_ATTACK};
enum HERO_SELECT {ATTACK, PARRY, FLEE, MEME};
